### Create a new tournament
POST http://localhost:8080/tournaments
Content-Type: application/json

{
  "tournamentname": "New York Tournament",
  "location": "New York",
  "startDate": "2024-09-20",
  "endDate": "2024-09-21",
  "time": "10:00:00",
  "status": "UPCOMING",
  "description": "Test Tournament",
  "winnerId": null,
  "players": []
}

### Retrieve all tournaments
GET http://localhost:8080/tournaments

### Retrieve a specific tournament by ID
GET http://localhost:8080/tournaments/1

### Retrieve a specific tournament by ID that doesnt exist
GET http://localhost:8080/tournaments/4

### Update a tournament
PUT http://localhost:8080/tournaments/1
Content-Type: application/json

{
  "tournamentname": "New York Tournament",
  "location": "Los Angeles",
  "startDate": "2024-09-22",
  "endDate": "2024-09-23",
  "time": "12:00:00",
  "status": "ONGOING",
  "description": "Updated Tournament",
  "winnerId": 3,
  "players": [3, 4]
}

### Update a tournament that doesnt exist
PUT http://localhost:8080/tournaments/4
Content-Type: application/json

{
  "tournamentname": "New York Tournament",
  "location": "Los Angeles",
  "startDate": "2024-09-22",
  "endDate": "2024-09-23",
  "time": "12:00:00",
  "status": "ONGOING",
  "description": "Updated Tournament",
  "winnerId": 3,
  "players": [3, 4]
}

### Delete a tournament
DELETE http://localhost:8080/tournaments/1

### Delete a tournament that doesnt exist
DELETE http://localhost:8080/tournaments/4

#Canica
###
POST http://localhost:8080/matches/create
Content-Type: application/json

{
    "tournament": {
        "id": 3
    },
    "user1": {
        "id": 1
    },
    "user2": {
        "id": 2
    },
    "matchDate": "2024-10-02",
    "matchTime": "12:00",
    "user1Score": 8,
    "user2Score": 7
}

DELETE http://localhost:8080/matches/9990
//Authorization: Basic admin:goodpassword

GET http://localhost:8080/matches/1

Authorization: Basic admin:goodpassword
POST http://localhost:8080/matches/create
Content-Type: application/json
Authorization: Basic admin:goodpassword
{
    "tournament": {
        "id": 1
    },
    "user1": {
        "id": 1
    },
    "user2": {
        "id": 2
    },
    "matchDate": "2024-10-02",
    "matchTime": "12:00",
    "user1Score": 8,
    "user2Score": 7
}



PUT http://localhost:8080/matches/create-update/1
Content-Type: application/json
Authorization: Basic admin:goodpassword
{
    "tournament": {
        "id": 1
    },
    "user1": {
        "id": 1
    },
    "user2": {
        "id": 2
    },
    "matchDate": "2024-10-02",
    "matchTime": "12:00",
    "user1Score": 9,
    "user2Score": 8
}



### 
# Get a specific match by ID (replace {id} with the actual match ID)
GET http://localhost:8080/matches/1L

### 
# Create a new match
POST http://localhost:8080/matches
Content-Type: application/json
Authorization: Basic admin:goodpassword

{
    "tournament": {
        "id": 1
    },
    "user1": {
        "id": 1
    },
    "user2": {
        "id": 2
    },
    "matchDate": "2024-10-02",
    "matchTime": "12:00",
    "user1Score": 8,
    "user2Score": 7
}

### 
# Update a match by ID (replace {id} with the actual match ID)
PUT http://localhost:8080/matches/1L
Content-Type: application/json
Authorization: Basic admin:goodpassword

{
    "tournament": {
        "id": 1
    },
    "user1": {
        "id": 1
    },
    "user2": {
        "id": 2
    },
    "matchDate": "2024-10-02",
    "matchTime": "12:00",
    "user1Score": 9,
    "user2Score": 8
}

### 
# Delete a match by ID (replace {id} with the actual match ID)
DELETE http://localhost:8080/matches/1L
Authorization: Basic admin:goodpassword





