### Create a new tournament
POST http://localhost:8080/tournaments
Content-Type: application/json

{
  "tournamentname": "New York Tournament",
  "location": "New York",
  "startDate": "2024-09-20",
  "endDate": "2024-09-21",
  "time": "10:00:00",
  "status": "UPCOMING",
  "description": "Test Tournament",
  "winnerId": null,
  "players": []
}

### Retrieve all tournaments
GET http://localhost:8080/tournaments

### Retrieve a specific tournament by ID
GET http://localhost:8080/tournaments/1

### Retrieve a specific tournament by ID that doesnt exist
GET http://localhost:8080/tournaments/4

### Update a tournament
PUT http://localhost:8080/tournaments/1
Content-Type: application/json

{
  "tournamentname": "New York Tournament",
  "location": "Los Angeles",
  "startDate": "2024-09-22",
  "endDate": "2024-09-23",
  "time": "12:00:00",
  "status": "ONGOING",
  "description": "Updated Tournament",
  "winnerId": 3,
  "players": [3, 4]
}

### Delete a tournament
DELETE http://localhost:8080/tournaments/1

### Delete a tournament that doesnt exist
DELETE http://localhost:8080/tournaments/4








GET http://localhost:8080/books

###
GET http://localhost:8080/books/abc

###
DELETE http://localhost:8080/books/1


###
POST http://localhost:8080/books
Content-Type: application/json
Authorization: Basic admin goodpassword

{
    "title": "The Great Ideas"
}
###
POST http://localhost:8080/books
Content-Type: application/json
Authorization: Basic admin goodpassword
# Validation failed - book title is null

{
    "name": "I, Robot"
}
###
PUT http://localhost:8080/books/1
Content-Type: application/json
# Wrong username
Authorization: Basic dt goodpassword

{
    "title": "The Return of the King"
}

###
GET http://localhost:8080/books/2/reviews


###
DELETE http://localhost:8080/books/2/reviews/2
Content-Type: application/json
Authorization: Basic gooduser:goodpassword

{
    "review": "Terrible :)"
}
###
POST http://localhost:8080/books/2/reviews
Content-Type: application/json
Authorization: Basic gooduser:goodpassword

{
    "review": "Should be good!"
}

###
PUT http://localhost:8080/books/2/reviews/2
Content-Type: application/json

{
    "review": "Should be bad!"
}

###
DELETE http://localhost:8080/books/1/reviews/5

###
GET http://localhost:8080/users

###
POST http://localhost:8080/users
Content-Type: application/json
Authorization: Basic admin goodpassword

{
    "username": "donta",
    "password": "goodpassword",
    "authorities": "ROLE_ADMIN"
}

###
POST http://localhost:8080/users
Content-Type: application/json
Authorization: Basic admin goodpassword

{
    "username": "gooduser",
    "password": "goodpassword",
    "authorities": "ROLE_USER"
}

###
GET http://localhost:8080/users
Content-Type: application/json
Authorization: Basic admin goodpassword

