GET http://localhost:8080/profiles

###
GET http://localhost:8080/users/2/profile/1
Content-Type: application/json

###
GET http://localhost:8080/users

###
POST http://localhost:8080/users/2/profile
Content-Type: application/json

{
    "firstname": "Bryan",
    "lastname": "Ng",
    "birthdate": "2000-01-01",
    "birthlocation": "Singapore",
    "organization": "SMU"
}

###
POST http://localhost:8080/users/3/profile
Content-Type: application/json

{
    "firstname": "Neha",
    "lastname": "Neha",
    "birthdate": "2003-01-01",
    "birthlocation": "Singapore"
}


###
PUT http://localhost:8080/user/2/profile/edit
Content-Type: application/json

{
    "firstname": "Glenn",
    "lastname": "Fann",
    "birthdate": "2000-01-01",
    "birthlocation": "Singapore",
    "organization": null  
}
